### ISSUE TITLE
whoisit does not find the RDAP endpoint for UK domains

### ISSUE THREAD

**Issue by Augustin-FL** [meeb/whoisit#13]
Hello,

It seems that there is some issue with uk domains

```
>>> whoisit.domain("citizensadvice.org.uk")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fl/.local/lib/python3.9/site-packages/whoisit/__init__.py", line 46, in domain
    method, url, exact_match = build_query(
  File "/home/fl/.local/lib/python3.9/site-packages/whoisit/query.py", line 57, in build
    url, exact_match = fetcher(query_value)
  File "/home/fl/.local/lib/python3.9/site-packages/whoisit/query.py", line 95, in get_domain_endpoint
    endpoints, exact_match = self.bootstrap.get_dns_endpoints(tld)
  File "/home/fl/.local/lib/python3.9/site-packages/whoisit/bootstrap.py", line 319, in get_dns_endpoints
    raise UnsupportedError(f'TLD "{tld}" has no known RDAP endpoint '
whoisit.errors.UnsupportedError: TLD "uk" has no known RDAP endpoint and is unsupported
```

Yet, .uk tld has an RDAP endpoint: https://rdap.nominet.uk/uk/domain/citizensadvice.org.uk

**Comment by meeb** [comment]
Nominet's RDAP enpoint isn't currently listed by the IANA which is why `.uk` domains currently aren't supported by default. I've added the RDAP endpoint as an optional override in the 2.6.1 release I've just pushed.

You can enable overrides by bootstrapping with the `overrides=True` kwarg, e.g.:

```python
whoisit.bootstrap(overrides=True)
```

The overrides are a set of manually specified RDAP endpoints which the IANA don't list at the moment. It's possible they also return non-standardised formatting for results as well so watch out for any weirdly parsed results if you enable them.

Update to 2.6.1 from PyPi and give it a go.

**Comment by case** [comment]
@meeb I wanted to thank you again for your time and effort maintaining this library -- very much appreciated!

**Comment by case** [comment]
It occurred to me that we could update the error message here, to make it a bit more user-friendly? e.g. mentioning the `overrides=True` instructions in the Readme. I'd be happy to make a PR for this, if you like the idea?

**Comment by meeb** [comment]
Not a bad idea @case, all good though I've just pushed a minor verbosity increase to the error message. I already had the edior open from the previous release. See: https://github.com/meeb/whoisit/commit/cda9a6f665b8d7b6ddf28e97273503012610afdf
