### ISSUE TITLE
Benchmarking whoisit against registrant name

### ISSUE THREAD

**Issue by baderdean** [meeb/whoisit#22]
Parsing Whois data is hard, especially because the format differ depending on the TLD. I've a specific issue with registrant value. So I decided to test multiple python whois library (pythonwhoisalt, asyncwhois, whoisit, whoisdomain) against the registrant field using google's domain dataset and check for their speed too. Initially, I was using whoisdomain, so here the initial post on its github: https://github.com/mboot-github/WhoisDomain/issues/21

Here the script I wrote: https://gist.github.com/baderdean/cc4643ecd95d3ccde31dee80ebdbea28

For whoisit, it's pretty normal only a few TLDs are supported because of RDAP support itself, yet only 3% looks to me too few. Did I miss something?

And here the results: 
```
{'asyncwhois': {'count': 49,
                'duration': 285.84409061399947,
                'percentage': 26,},
 'whoisdomain': {'count': 44,
                 'duration': 195.54051797400007,
                 'percentage': 24},
 'whoisit': {'count': 6,
             'duration': 27.91238160300054,
             'percentage': 3,},
'pythonwhoisalt': {'count': 7,
                    'duration': 1055.0711162629996,
                    'percentage': '4%'}}
```

PS: I've created similar issues in other projects as well.

**Comment by meeb** [comment]
Thanks, looks interesting! Your results might well be correct, the ccTLDs with RDAP servers is quite limited (loaded from https://data.iana.org/rdap/dns.json).

As your sample data is almost entirely the more esoteric ccTLDs I would expect there to be a significantly lower number of supported TLDs with RDAP endpoints than a those with traditional WHOIS servers.

You'll get *slightly* better coverage by bootstrapping `whoisit` with `whoisit.bootstrap(overrides=bool, allow_insecure=bool)` which adds in a few more ccTLDs, with the overrides being a manual list of TLDs and their RDAP endpoints:

https://github.com/meeb/whoisit/blob/main/whoisit/overrides.py

And `allow_insecure=True` to enable some of the less sane RDAP services, e.g. `.uz` for `google.co.uz` has an RDAP server but it's disabled by default due to having no SSL support at all.

There's a helper script here that iterates the root zone file and lists TLDs which have registered RDAP endpoints here:

https://github.com/meeb/whoisit/blob/main/tools/list_public_tlds_with_rdap_endpoints.py

Example output:

https://gist.github.com/meeb/ea5ec4ff30d036f0cba2047cc2d07504

A quick scan and you can see that pretty much all of the "UNSUPPORTED" domains are the ccTLDs you're testing against.

**Comment by baderdean** [comment]
Hello,

Thanks for your detailed answer.

I understand that RDAP is limited, but if this is the future and cover enough TLD it's good to go.

Yet, the "UNSUPPORTED" are 286 in your example output file and major TLDs are UNSUPPORTED like .au (Australia), .at (Austria), .dk (Denmark),  .eu (Europe), .it (Italia), .ir (Ireland) .me, .am, .jp (Japan). edu (USA education) and a few others.

My conclusion is that we could use RDAP and rely on legacy whois when RDAP is unavailable but one can't rely on RDAP only in a global context. The only issue I've got is having to use 2 library (RDAP/WHOIS) with different syntax instead of only one or two with the same result data model.

**Comment by meeb** [comment]
Yes to have as much coverage as possible you'll need to try RDAP then fall back to WHOIS. Obviously not all ccTLDs have WHOIS services either so I doubt you'll ever get total coverage. WHOIS support is outside the scope of `whoisit` though.

**Comment by meeb** [comment]
Do you have anything you'd like to add or suggest here or should I close the issue?
