### ISSUE TITLE
notice returns as dict

### ISSUE THREAD

**Issue by askkemp** [meeb/whoisit#32]
With v2.7.7, a query against the below domain returns `notice` as a dict instead of an expected list which causes line 118 of parser.py raise an exception.

```python
whoisit.domain('achimmuenster.info', allow_insecure_ssl=False, raw=False)
```

```python
...
File /opt/conda/lib/python3.11/site-packages/whoisit/parser.py:118, in Parser.extract_notices(self)
    116 self.parsed['copyright_notice'] = ''
    117 for notice in self.raw_data.get('notices', []):
--> 118     title = clean(notice.get('title', '')).lower()
    119     if title in (
    120             'terms of service', 'terms of use', 'terms and conditions'
    121     ):
    122         links = notice.get('links', [])

AttributeError: 'str' object has no attribute 'get'
```
```python
...
    ],
    "notices": {
        "title": "401 Unauthorized",
        "description": "Path 'domain': Quota exceeded (31/30) for <ip4 address redacted>",
    },
...
```

What is unusual is that even though the notice received says the quota is exceeded, it still returns the requested information.

**Comment by meeb** [comment]
Thanks for the issue. This would appear to be because as of the latest release if the primary results from the TLD RDAP endpoint returns a referral related upstream RDAP endpoint that will also be queried as it likely has more information. This is overlayed on the original information to improve details and accuracy. What seems to be happening in this case is the primary RDAP endpoint query is working, but the upstream RDAP query is rate limiting your IP address.

I'll see if it's sensible to either fail the query entirely or if upstream RDAP queries should quietly fail and maybe emit a warning.

In the interim, you should be able to use `follow_related=False` to disable the related upstream secondary RDAP query which should prevent this error from occurring for you (or wait for your query quota for your IP to expire).

**Comment by meeb** [comment]
There's some basic type checking in the latest 3.0.0 release. This will still error (when your IP address gets throttled) but the error should be clearer at least. You should probably just try a fallback to catch this or hard error if you're rate limited. Something like:

```python
from whoisit.errors import RateLimitedError

try:
    # Try a normal look up and follow related info links
    results = whoisit.domain('some.domain')
except RateLimitedError:
    # Got rate limited, attempt the same lookup but without following related info links
    results = whoisit.domain('some.domain', follow_related=False)
    # If this still errors you've been rate limited on the first, main, RDAP endpoint and you should abort
```

Given `whoisit` can't account for your IP being rate limited I'll close this for now, but feel free to let me know if you have any other issues.

**Comment by raffysommy** [comment]
> 
> ```python
> from whoisit.errors import RateLimitedError
> 
> try:
>     # Try a normal look up and follow related info links
>     results = whoisit.domain('some.domain')
> except RateLimitedError:
>     # Got rate limited, attempt the same lookup but without following related info links
>     results = whoisit.domain('some.domain', follow_related=False)
>     # If this still errors you've been rate limited on the first, main, RDAP endpoint and you should abort
> ```

Hey,
Thanks for the amazing project. Instead of this approach, it would be good to have a flag to store the content the library crawled so far without having to query (and bother) again the TLD RDAP server. Would be possible to implement that?
Thanks :)

**Comment by meeb** [comment]
@raffysommy do you mean something like store a work queue of URLs inside of whoisit and have some sort of retry feature for failures? If so that is something you would definitely build in your application and I wouldn't think that would be a good fit for whoisit itself. As a library whoisit should just do a lookup and some parsing, more complicated deployments would be up to the applications importing whoisit.

**Comment by meeb** [comment]
Ah, gotcha. I did consider that, but it would result in some pretty random behavior of the upstream failed but the initial request succeeded, you could get two different results for the same query with no real way to know. I suppose I could attach the initial request results to the exception so applications could decide for themselves if they wanted to use it or not if the upstream referral request failed.

**Comment by raffysommy** [comment]
@meeb exactly I was thinking of that, having it as part of the exception would be great.
