### ISSUE TITLE
Improving whoisit.errors.RateLimitedError

### ISSUE THREAD

**Issue by askkemp** [meeb/whoisit#34]
The `whoisit.errors.RateLimitedError` exception is set to occur on an HTTP response code of 429. However, some RDAP servers respond with HTTP 403 or 422 which instead provides `whoisit.errors.QueryError`. I believe it is important to raise RateLimitedError when known.

For example, https://rdap.nic.abogado returns HTTP 403 with a body of:
```html
<HTML><HEAD><TITLE>Number of allowed queries exceeded.
</TITLE></HEAD><BODY><h3>403 Forbidden</h3><div>Number of allowed queries exceeded.
</div></BODY>
```

For example, https://rdap.nic.biz, returns HTTP 403 with a body of:
```html
<HTML><HEAD><TITLE>Number of allowed queries exceeded.
</TITLE></HEAD><BODY><h3>403 Forbidden</h3><div>Number of allowed queries exceeded.
</div></BODY>
```

For example, https://rdap.zdnsgtld.com returns HTTP 422 with a body of:
```json
{
    "rdapConformance": [
        "icann_rdap_response_profile_0",
        "icann_rdap_technical_implementation_guide_0",
        "rdap_level_0"
    ],
    "errorCode": "422",
    "title": "Forbidden request",
    "description": [
        "Your access is too fast,please try again later."
    ],
...
}
```

Looking at the [RFC](https://www.rfc-editor.org/rfc/rfc7480) , it does not provide a specific response code for ratelimiting but instead just says:
> If the receiving server will not answer a request for policy reasons, it will return an error response (4xx) indicating the reason for giving no answer.

Maybe in query.py, known indications of rate limited can be checked so it is better guaranteed that the `whoisit.errors.RateLimitedError` exception occurs? For example:

```python
        elif ((response.status_code >= 400 and response.status_code <= 499) and 
              ("Your access is too fast" in response.text or 
               "Number of allowed queries exceeded" in response.text)):        
            raise RateLimitedError(f'RDAP {self.method} request to {self.url} '
                                   f'returned a {response.status_code} error, the resource has been '
                                   f'rate limited')
```

If this something you're willing to consider, I'm glad to start collecting phrases from the response body that suggest rate limiting has occurred.

**Comment by meeb** [comment]
Thanks for the issue. Like you I have noticed a wide variance in RDAP endpoint behaviors, rate limits and error codes. Especially with the override endpoints that are even less compliant. I can see what you're suggesting but that's probably too arduous to maintain. Some of the RDAP endpoint error messages aren't in English so collecting those would be tedious and prone to translation errors. It's likely an endless task to try and account for every eventuality by checking text strings and if the correct exception isn't raised it'll be confusing for anyone who relies on it. Looking at the HTTP status code is about the only sensible way.

I will push a patch shortly to make catching 403's and 422's easier, I'll also tweak the exception inheritance tree so you can also just catch `QueryError` for all errors rather than `WhoisitError` which is also used for more general non-query errors.

If you have an application which queries an RDAP endpoint that erroneously returns a 403 for rate limiting you can obviously check the error text yourself in your code to decide how to behave but I probably wouldn't want a fuzzy list of text that changes the exception raised in `whoisit` directly. Happy to add checks for various HTTP status codes returned if you collect them of course, that information is most useful.

**Comment by meeb** [comment]
In the above commits I've tweaked error handling such that:

1. You can now catch `QueryError` for all query errors, this will now catch all non-200 responses:

```python
try:
    whoisit.domain('blahblahdoesnotexist.biz')
except whoisit.errors.QueryError as e:
    print(e)
```

2. Additionally, all `QueryError` exceptions raised now pass down the raw message and HTTP status code from the upstream RDAP endpoint which you can check in your application to decide how to handle the response:

```python
try:
    whoisit.domain('blahblahdoesnotexist.biz')
except whoisit.errors.QueryError as e:
    print(e)
    if e.status_code == 422 and 'your access is too fast' in e.response.lower():
        # decide how to handle this in your application
        some_retry_logic()
```

If the `QueryError` is raised for a non-HTTP related issue (SSL handshake failed, request timeout etc.) then `QueryError.status_code` will be `0` and `QueryError.response` will be `''`.

This should be a reasonable middle ground of allowing people to code better error handling without having to stuff in per-endpoint error management code into `whoisit`. Is this sufficient for your usage?

**Comment by askkemp** [comment]
This is absolutely perfect! Thank you.

**Comment by meeb** [comment]
No problem. I'll need to make sure the above new behavior is replicated in the new async interface. There also may still be some weird issues if the primary request succeeds but the sub-request (following related info links) fails which you'll probably have to account for. Once that's all done and tested this will be bundled into the next release.

**Comment by meeb** [comment]
This is bundled into the latest v3.0.1 release so I'll close this for now. Feel free to comment back if you have further issues.
